### PR TITLE
feature: allow providing kubeconfig from string

### PR DESCRIPTION
**Pull request by christiangebhard**
This should resolve https://github.com/manusa/helm-java/issues/52 , providing the option to use the contents of a kubeconfig instead of a file directly. 

Disclaimer: I'm no go expert so the tests are a bit spartanic.

### CODE REVIEW

**Comment by manusa** [comment]
Thanks for contributing, I'll review deeper as soon as I get some time.

From the first look, I think I'd prefer an approach where the `kubeconfig` contents was persisted in Java to a temporary file and then passed as a path to the go side of things (the file should be deleted after the Java execution).
However, this might not be very good security-wise.

On the other hand, your current approach is quite convoluted and might have multiple unwanted side-effects for more complex configurations. I'm not sure if you ported the client-go instantiation from `helm` or not. I'd need check this further.

**Comment by christiangebhard** [comment]
Thanks for the first feedback. I totally understand your concerns about my approach. I did choose this over a temporary file, like you said for security reasons. If you think these concerns are unnecessary let me know and I can change the implementation. 
The client-go instantiation is inspired by this discussion here https://github.com/helm/helm/issues/6910 and from browsing through the helm code.

**Comment by manusa** [comment]
After a few hours of digging into client-go's source code I think I managed to find a simple solution that is both secure and sustainable in the future.

Please take a look to see if this works for you. The tests seem to be passing fine.

I think another iteration is needed to make it work completely fine without side-effects, but it should probably be tackled as a separate pull request.

**Comment by christiangebhard** [comment]
Thanks for your work, this works completely fine for our use case (https://github.com/manusa/helm-java/issues/52#issuecomment-2468611003) - looking forward to use the release :)

**Pull request merged**
